# Generated by Django 5.0.7 on 2024-09-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
